Repository maple-labs/maple-core, pull requests merged in 2021-04, with the labels that each got.

#363 feat: Improve the flattening script by handling the licenses
  flatten.sh
Labels: No Functionality Changes, Status: Ready for Review, Type: Enhancement

#364 chore: NatSpec C4 fixes and normalization (SC-2032)
  contracts/CollateralLocker.sol
  contracts/DebtLocker.sol
  contracts/FundingLocker.sol
  contracts/LiquidityLocker.sol
  contracts/Loan.sol
  contracts/LoanFactory.sol
  contracts/MapleGlobals.sol
  contracts/MapleTreasury.sol
  contracts/MplRewards.sol
  contracts/MplRewardsFactory.sol
  contracts/Pool.sol
  contracts/PoolFactory.sol
  contracts/StakeLocker.sol
  contracts/library/LoanLib.sol
  contracts/library/PoolLib.sol
  contracts/oracles/ChainlinkOracle.sol
  contracts/oracles/UsdOracle.sol
  contracts/token/BasicFDT.sol
  contracts/token/ExtendedFDT.sol
  contracts/token/FDT.sol
  contracts/token/IFDT.sol
  contracts/token/PoolFDT.sol
  contracts/token/StakeLockerFDT.sol
Labels: Priority: Medium, Status: Approved, Type: Chore

#361 chore: Add link to audit report in README (SC-1944)
  README.md
Labels: No Functionality Changes, Priority: Low, Status: Revisions Needed, Type: Chore

#357 feat: Refactor Pool tests to use fuzzing (SC-1905)
  contracts/test/Loan.t.sol
  contracts/test/PoolClaim.t.sol
  contracts/test/PoolDelegate.t.sol
  contracts/test/PoolLiquidation.t.sol
  contracts/test/PoolLiquidityProvider.t.sol
  contracts/test/TestUtil.sol
Labels: No Functionality Changes, Priority: High, Status: Ready for Review, Type: Enhancement

#368 chore: C4 event updates and normalization (SC-2034)
  contracts/CollateralLockerFactory.sol
  contracts/DebtLockerFactory.sol
  contracts/FundingLockerFactory.sol
  contracts/LiquidityLockerFactory.sol
  contracts/Loan.sol
  contracts/LoanFactory.sol
  contracts/MapleGlobals.sol
  contracts/MapleTreasury.sol
  contracts/MplRewards.sol
  contracts/MplRewardsFactory.sol
  contracts/Pool.sol
  contracts/PoolFactory.sol
  contracts/StakeLocker.sol
  contracts/StakeLockerFactory.sol
  contracts/library/PoolLib.sol
  contracts/oracles/ChainlinkOracle.sol
  contracts/test/TestUtil.sol
  contracts/token/BasicFDT.sol
  contracts/token/ExtendedFDT.sol
Labels: Priority: High, Status: Revisions Needed, Type: Chore

#369 chore: Removing TODOs (SC-2042)
  contracts/Pool.sol
  contracts/StakeLocker.sol
  contracts/library/PoolLib.sol
Labels: Priority: Low, Status: Ready for Review, Type: Chore

#365 chore: Error Messages C4 fixes and normalization (SC-2036)
  contracts/CollateralLocker.sol
  contracts/DebtLocker.sol
  contracts/FundingLocker.sol
  contracts/LiquidityLocker.sol
  contracts/Loan.sol
  contracts/LoanFactory.sol
  contracts/MapleGlobals.sol
  contracts/MapleTreasury.sol
  contracts/MplRewards.sol
  contracts/MplRewardsFactory.sol
  contracts/Pool.sol
  contracts/PoolFactory.sol
  contracts/StakeLocker.sol
  contracts/library/LoanLib.sol
  contracts/library/PoolLib.sol
  contracts/math/SafeMathInt.sol
  contracts/math/SafeMathUint.sol
  contracts/oracles/ChainlinkOracle.sol
  contracts/token/BasicFDT.sol
  contracts/token/ExtendedFDT.sol
Labels: Priority: Medium, Status: Merge Conflicts, Type: Chore

#367 fix: Pass in fundingPeriod from Loan storage (SC-2044)
  contracts/Loan.sol
  contracts/library/LoanLib.sol
Labels: Priority: High, Status: Ready for Review, Type: Bug

#372 refactor: Simplified/Cleaner updateDate logic (SC-2074)
  contracts/StakeLocker.sol
  contracts/library/PoolLib.sol
  contracts/test/StakeLocker.t.sol
Labels: Priority: Medium, Type: Enhancement

#376 chore: fix the PD transferFrom restriction in StakeLocker
  contracts/StakeLocker.sol
  contracts/test/StakeLocker.t.sol
Labels: Priority: High, Status: Ready for Review, Type: Chore

#377 feat: Remove inconsistency from the auth model
  contracts/Pool.sol
  contracts/StakeLocker.sol
  contracts/interfaces/IPool.sol
  contracts/test/PoolDelegate.t.sol
  contracts/test/StakeLocker.t.sol
  contracts/test/user/PoolDelegate.sol
Labels: Priority: High, Status: Approved, Type: Enhancement

#374 feat: C4 validations (SC- 2040)
  contracts/oracles/ChainlinkOracle.sol
  contracts/test/ChainLinkOracle.t.sol
Labels: Priority: High, Status: Approved, Type: Enhancement

#373 refactor: Gas Optimizations (C4 and other) (SC-2038)
  contracts/CollateralLockerFactory.sol
  contracts/DebtLocker.sol
  contracts/DebtLockerFactory.sol
  contracts/FundingLockerFactory.sol
  contracts/LateFeeCalc.sol
  contracts/LiquidityLockerFactory.sol
  contracts/Loan.sol
  contracts/LoanFactory.sol
  contracts/MapleGlobals.sol
  contracts/MapleTreasury.sol
  contracts/MplRewards.sol
  contracts/MplRewardsFactory.sol
  contracts/Pool.sol
  contracts/PoolFactory.sol
  contracts/PremiumCalc.sol
  contracts/RepaymentCalc.sol
  contracts/StakeLocker.sol
  contracts/StakeLockerFactory.sol
  contracts/library/LoanLib.sol
  contracts/library/PoolLib.sol
  contracts/library/Util.sol
  contracts/math/SafeMathUint.sol
  contracts/oracles/ChainlinkOracle.sol
  contracts/token/BasicFDT.sol
  contracts/token/ExtendedFDT.sol
Labels: Priority: Medium, Status: Ready for Review, Type: Enhancement

#366 feat: Use ERC-2258 in PoolFDT to allow for farming + interest (SC-2046)
  contracts/MplRewards.sol
  contracts/Pool.sol
  contracts/interfaces/IERC2258.sol
  contracts/interfaces/IPool.sol
  contracts/library/PoolLib.sol
  contracts/test/MplRewards.t.sol
  contracts/test/PoolCustodial.t.sol
  contracts/test/PoolDelegate.t.sol
  contracts/test/PoolLiquidityProvider.t.sol
  contracts/test/StakeLocker.t.sol
  contracts/test/TestUtil.sol
  contracts/test/user/Custodian.sol
  contracts/test/user/Farmer.sol
  contracts/test/user/Governor.sol
  test.sh
Labels: Priority: High, Status: Ready for Review, Type: Bug

#378 feat: Restrict transfers during lockup period (SC-2045)
  contracts/Pool.sol
  contracts/StakeLocker.sol
  contracts/interfaces/IERC2258.sol
  contracts/library/PoolLib.sol
  contracts/test/PoolCustodial.t.sol
  contracts/test/PoolLiquidityProvider.t.sol
  contracts/test/StakeLocker.t.sol
  contracts/test/TestUtil.sol
  contracts/test/user/PoolDelegate.sol
Labels: Priority: High, Status: Approved, Type: Bug

#375 chore: Comments, Spelling, and NatSpec cleanup (SC-2083)
  contracts/CollateralLocker.sol
  contracts/CollateralLockerFactory.sol
  contracts/DebtLocker.sol
  contracts/DebtLockerFactory.sol
  contracts/FundingLocker.sol
  contracts/FundingLockerFactory.sol
  contracts/LateFeeCalc.sol
  contracts/LiquidityLocker.sol
  contracts/LiquidityLockerFactory.sol
  contracts/Loan.sol
  contracts/LoanFactory.sol
  contracts/MapleGlobals.sol
  contracts/MapleTreasury.sol
  contracts/MplRewards.sol
  contracts/MplRewardsFactory.sol
  contracts/Pool.sol
  contracts/PoolFactory.sol
  contracts/RepaymentCalc.sol
  contracts/StakeLocker.sol
  contracts/StakeLockerFactory.sol
  contracts/library/LoanLib.sol
  contracts/library/PoolLib.sol
  contracts/library/Util.sol
  contracts/oracles/ChainlinkOracle.sol
  contracts/oracles/IChainlinkAggregatorV3.sol
  contracts/oracles/UsdOracle.sol
  contracts/token/BasicFDT.sol
  contracts/token/ExtendedFDT.sol
  contracts/token/FDT.sol
  contracts/token/PoolFDT.sol
  contracts/token/StakeLockerFDT.sol
Labels: No Functionality Changes, Priority: Low, Status: Approved, Type: Chore

#379 feat: Update `collateralRequiredForDrawdown` conversion approach (SC-2086)
  contracts/Pool.sol
  contracts/library/LoanLib.sol
Labels: Priority: High, Status: Ready for Review, Type: Bug

#383 chore: Fixed an emit of CustodyAllowanceChanged, and some cleanup (SC-2092)
  contracts/DebtLocker.sol
  contracts/LateFeeCalc.sol
  contracts/Loan.sol
  contracts/MapleGlobals.sol
  contracts/Pool.sol
  contracts/PremiumCalc.sol
  contracts/RepaymentCalc.sol
  contracts/StakeLocker.sol
  contracts/interfaces/IDebtLocker.sol
  contracts/interfaces/ILiquidityLocker.sol
  contracts/interfaces/ILoan.sol
  contracts/interfaces/ILoanFactory.sol
  contracts/interfaces/IMapleGlobals.sol
  contracts/interfaces/IOracle.sol
  contracts/interfaces/IPool.sol
  contracts/interfaces/IStakeLocker.sol
  contracts/library/LoanLib.sol
  contracts/library/PoolLib.sol
  contracts/library/Util.sol
  contracts/oracles/ChainlinkOracle.sol
  contracts/test/PoolClaim.t.sol
  contracts/test/PoolFactory.t.sol
  contracts/test/StakeLocker.t.sol
  contracts/test/TestUtil.sol
  contracts/test/user/Borrower.sol
  contracts/test/user/Commoner.sol
  contracts/test/user/Governor.sol
  contracts/test/user/LP.sol
  contracts/test/user/Lender.sol
  contracts/test/user/PoolDelegate.sol
  contracts/test/user/Staker.sol
  contracts/token/BasicFDT.sol
  contracts/token/ExtendedFDT.sol
  contracts/token/PoolFDT.sol
  contracts/token/StakeLockerFDT.sol
  contracts/token/interfaces/IExtendedFDT.sol
  contracts/token/interfaces/IFDT.sol
  contracts/token/interfaces/IStakeLockerFDT.sol
Labels: Priority: Medium, Status: Ready for Review, Type: Chore

#381 refactor: Refactor tests to use $3m of Balancer pool liquidity (SC-2060)
  contracts/test/Gulp.t.sol
  contracts/test/PoolDelegate.t.sol
  contracts/test/PoolLiquidation.t.sol
  contracts/test/TestUtil.sol
Labels: Priority: High, Status: Ready for Review, Type: Chore

#382 feat: Add late fees to makeFullPayment (SC-2087)
  contracts/Loan.sol
  contracts/library/LoanLib.sol
  contracts/test/Calcs.t.sol
  contracts/test/PoolClaim.t.sol
Labels: Priority: High, Status: Ready for Review, Type: Enhancement

#385 feat: Add ERC-2258 functionality to StakeLocker (SC-2089)
  contracts/MapleGlobals.sol
  contracts/Pool.sol
  contracts/StakeLocker.sol
  contracts/interfaces/IMapleGlobals.sol
  contracts/interfaces/IStakeLocker.sol
  contracts/library/PoolLib.sol
  contracts/test/MapleGlobals.t.sol
  contracts/test/PoolCustodial.t.sol
  contracts/test/StakeLockerCustodial.t.sol
  contracts/test/TestUtil.sol
  contracts/test/user/Custodian.sol
  contracts/test/user/Governor.sol
  contracts/test/user/Staker.sol
Labels: Priority: High, Status: Ready for Review, Type: Enhancement

#384 refactor: reduce end-user gas costs with Pool
  contracts/MapleGlobals.sol
  contracts/Pool.sol
  contracts/interfaces/IMapleGlobals.sol
  contracts/library/PoolLib.sol
Labels: Priority: Low, Status: Ready for Review, Type: Enhancement

#388 chore: Post-C4 Re-review Changes (SC-2103)
  contracts/Loan.sol
  contracts/LoanFactory.sol
  contracts/MapleGlobals.sol
  contracts/MapleTreasury.sol
  contracts/MplRewards.sol
  contracts/Pool.sol
  contracts/StakeLocker.sol
  contracts/interfaces/IERC2258.sol
  contracts/interfaces/ILoan.sol
  contracts/interfaces/IMplRewards.sol
  contracts/library/LoanLib.sol
  contracts/library/PoolLib.sol
  contracts/oracles/ChainlinkOracle.sol
  contracts/test/Loan.t.sol
  contracts/test/LoanFactory.t.sol
  contracts/test/MapleTreasury.t.sol
  contracts/test/MplRewards.t.sol
  contracts/test/PoolClaim.t.sol
  contracts/test/PoolCustodial.t.sol
  contracts/test/PoolDelegate.t.sol
  contracts/test/PoolLiquidityProvider.t.sol
  contracts/test/StakeLocker.t.sol
  contracts/test/StakeLockerCustodial.t.sol
  contracts/test/TestUtil.sol
  contracts/test/user/Borrower.sol
  contracts/test/user/Farmer.sol
  contracts/test/user/Governor.sol
  contracts/test/user/LP.sol
  contracts/test/user/Lender.sol
  contracts/test/user/PoolDelegate.sol
  contracts/test/user/Staker.sol
  contracts/token/BasicFDT.sol
  contracts/token/ExtendedFDT.sol
  contracts/token/LoanFDT.sol
  contracts/token/PoolFDT.sol
  contracts/token/StakeLockerFDT.sol
  contracts/token/interfaces/IBaseFDT.sol
  contracts/token/interfaces/ILoanFDT.sol
  contracts/token/interfaces/IStakeLockerFDT.sol
Labels: Priority: High, Status: Ready for Review, Type: Chore

#389 fix: Prevent investorFee and treasuryFee globals overflow
  contracts/MapleGlobals.sol
  contracts/test/MapleGlobals.t.sol
Labels: Priority: High, Status: Approved, Status: Ready for Review, Type: Bug

#390 chore: Minor corrections from final review
  contracts/Loan.sol
  contracts/LoanFactory.sol
  contracts/MapleGlobals.sol
  contracts/MplRewardsFactory.sol
  contracts/Pool.sol
  contracts/PoolFactory.sol
  contracts/PremiumCalc.sol
  contracts/RepaymentCalc.sol
  contracts/StakeLocker.sol
  contracts/library/LoanLib.sol
  contracts/library/PoolLib.sol
  contracts/oracles/IChainlinkAggregatorV3.sol
  contracts/test/PoolDelegate.t.sol
  contracts/token/BasicFDT.sol
  contracts/token/ExtendedFDT.sol
  contracts/token/LoanFDT.sol
  contracts/token/StakeLockerFDT.sol
Labels: No Functionality Changes, Priority: Medium, Status: Ready for Review, Type: Chore

#391 fix: Update Loan spec fuzzing
  contracts/test/TestUtil.sol
Labels: Priority: High, Status: Ready for Review, Type: Chore
