Repository maple-labs/maple-core, pull requests merged in 2021-05, with the labels that each got.

#394 feat: Update logo and audit reports in README
  README.md
Labels: Priority: Medium, Status: Ready for Review, Type: Chore

#393 feat: Add dedicated interest/loss PoolFDT fuzz testing (SC-2051)
  contracts/test/PoolFDTLosses.t.sol
  contracts/test/TestUtil.sol
  contracts/test/user/LP.sol
Labels: No Functionality Changes, Priority: Low, Status: Ready for Review, Type: Enhancement

#397 feat: Test Script Arguments
  test.sh
Labels: No Functionality Changes, Priority: Medium, Status: Ready for Review, Type: Enhancement

#401 feat: Add deployed addresses to README (SC-2257)
  .circleci/config.yml
  README.md
Labels: Priority: Medium, Status: Ready for Review, Type: Chore

#402 feat: Committed Flattened Contracts
  .gitignore
  flatten.sh
  flattened-contracts/ChainlinkOracle.sol
  flattened-contracts/CollateralLocker.sol
  flattened-contracts/CollateralLockerFactory.sol
  flattened-contracts/DebtLocker.sol
  flattened-contracts/DebtLockerFactory.sol
  flattened-contracts/FundingLocker.sol
  flattened-contracts/FundingLockerFactory.sol
  flattened-contracts/IChainlinkAggregatorV3.sol
  flattened-contracts/LateFeeCalc.sol
  flattened-contracts/LiquidityLocker.sol
  flattened-contracts/LiquidityLockerFactory.sol
  flattened-contracts/Loan.sol
  flattened-contracts/LoanFactory.sol
  flattened-contracts/LoanLib.sol
  flattened-contracts/MapleGlobals.sol
  flattened-contracts/MapleTreasury.sol
  flattened-contracts/MplRewards.sol
  flattened-contracts/MplRewardsFactory.sol
  flattened-contracts/Pool.sol
  flattened-contracts/PoolFactory.sol
  flattened-contracts/PoolLib.sol
  flattened-contracts/PremiumCalc.sol
  flattened-contracts/RepaymentCalc.sol
  flattened-contracts/StakeLocker.sol
  flattened-contracts/StakeLockerFactory.sol
  flattened-contracts/UsdOracle.sol
  flattened-contracts/Util.sol
Labels: Priority: Medium, Status: Ready for Review

#403 fix: Update Rinkeby Etherscan links
  README.md
Labels: Priority: Medium, Status: Ready for Review, Type: Chore

#404 fix: Update Rinkeby Etherscan links
  README.md
Labels: Priority: Medium, Status: Ready for Review, Type: Chore
